simplify error conversion
nickray/littlefs2 pull request #11
Opened 2021-05-27 21:14 UTC by conorpp

Did this while figuring out what ended up being an unrelated error.  I think it's a bit simpler and takes up ~600 less bytes in program space.

2021-05-28 10:35 UTC, nickray requested changes

2021-05-28 10:35 UTC, nickray commented on src/fs.rs
> +        io::result_from_error(return_code)
This should be `io::result_from(read as usize, return_code)` I think? (And the following two with position/written).

2021-06-01 04:46 UTC, conorpp commented on src/fs.rs
> +        io::result_from_error(return_code)
My thought was that casting it to usize before checking if it's negative was a bit weird, but it works in any event.

2021-06-01 04:51 UTC, conorpp commented
@nickray addressed comment

2021-06-03 16:42 UTC, nickray commented
Maybe I misunderstood, I thought the read/write methods were no longer returning the number of bytes they actually read/wrote. Was this already the case before addressing? And/or is it now? If I remember correctly, one cannot assume that everything will be read/written in one go.

2021-06-03 17:55 UTC, conorpp commented
I didn't change anything functionally, just refactored.  All the return values are the same, so yes still being returned and was the case before.

2021-06-04 08:58 UTC, merged